### ISSUE TITLE
Bug: Rolelocking will not work with roles with spaces in it unless mentioned

### ISSUE THREAD

**Issue by MrCamel999** [ComputerMaster1st/RailgunVB#12]
Server ID: 492563500581781505 Message ID: 505921657030836246. Won’t work for some reason idk why so just reporting here.

**Comment by ComputerMaster1st** [comment]
Welp, there goes the "bug free" award. I'll get right on this.

**Comment by ComputerMaster1st** [comment]
This has now been solved. ;)
