### ISSUE TITLE
Warn system error

### ISSUE THREAD

**Issue by randoomx8** [ComputerMaster1st/RailgunVB#13]
**rgwarn <@mention> [reason]** does not state in the documentation that it needs the bot to be able to ban people. 
Using the command prompts the following: Command Error: I do not have permission to perform this command! SERVER-PERM-MISSING : BanMembers

**Comment by ComputerMaster1st** [comment]
Hi There,

The warn system has an "auto-ban" built-in which is why it requests for ban permissions. I'll add it to the wiki.

Regards,

CM1
