### ISSUE TITLE
I know it's silly but....

### ISSUE THREAD

**Issue by dragonriderworld** [ComputerMaster1st/RailgunVB#16]
would it be possible for you to bring out a second RG? 
Backround Infos:

Me and my friends have a Discord for Gaming. And some want to only hear music(Its a Radio-Channel). In this voicechat they want to disable speaking. But at the same time they want a music bot in their Gaming-VoiceChat, in which they can speak, etc. And the want RG xD (me too its the best^^)

But dont feel forced to do that....I know its silly but maybe its possible xD
You did much for me until now...
Thanks
GameofDragons

**Comment by ComputerMaster1st** [comment]
Hi There,

This is the first time someone asked for a 2nd Railgun. I'm not sure how to respond to this. If I created a 2nd Railgun, some of it's code may have to be rewritten so it won't have any of the automated functionality. There may be a few other things that'll need addressing. With the way Railgun is at this time, it sadly isn't possible.

However, I do have an idea which could make this possible but I'm not entirely sure.

**Comment by dragonriderworld** [comment]
Ll thx. Thats more than i expected. :)

**Comment by ComputerMaster1st** [comment]
Oke, I've decided not to create a 2nd Railgun. However, I shall make a 2nd one provided there's enough demand. ;)

For now, this issue shall be closed. But, may be re-opened in the future.
