### ISSUE TITLE
Delete this.

### ISSUE THREAD

**Issue by LewisTehMinerz** [ComputerMaster1st/RailgunVB#20]
VB is the tumor of .NET. Rewrite in C#.

**Comment by ComputerMaster1st** [comment]
Make me! :P

**Comment by LewisTehMinerz** [comment]
cunt

**Comment by LewisTehMinerz** [comment]
thank you

**Comment by Chewsterchew** [comment]
👍

**Comment by 1024x2** [comment]
this is high quality github usage

**Comment by 1024x2** [comment]
actually rewrite in node.js :^)

**Comment by LewisTehMinerz** [comment]
rewrite in go, more readable than this bullshit

**Comment by ComputerMaster1st** [comment]
> actually rewrite in node.js :^)

Hell no!

**Comment by 1024x2** [comment]
use discord.js :^))))))

**Comment by Chewsterchew** [comment]
use discordcr, the true language of the future

**Comment by 1024x2** [comment]
no, use discordasm :^)))))))))))))))))))))))))))))))))))

**Comment by LewisTehMinerz** [comment]
i won the bet i made, he has to rewrite it in c#
