### ISSUE TITLE
Bug: Can’t seem to upload music to bot through YT Playlist

### ISSUE THREAD

**Issue by MrCamel999** [ComputerMaster1st/RailgunVB#7]
Error message came up when I tried adding music to my server. Could be I have too much music for my server (880 songs rn). Hope this gets patched, but just leaving this here for info. Thanks!

**Comment by ComputerMaster1st** [comment]
There's no limit to how many songs you can have. As for the error, what was it?

**Comment by ComputerMaster1st** [comment]
Problem most likely resolved itself. Create new issue or re-open this one if the same error occurs.
